on:
  - push
  - pull_request

jobs:
  install-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm config set registry https://registry.npmmirror.com/ && pnpm install
        
      - name: Build packages
        run: pnpm run build
      
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r notice-master-client.zip packages/host/dist/

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: notice-master-client
          # A file, directory or wildcard pattern that describes what to upload
          path: notice-master-client.zip
          # The desired behavior if no files are found using the provided path.
      - name: Upload to cdn
        uses: saltbo/uptoc@v1.4.3
        with:
          # specify driver for the cloud platform
          driver: qiniu
          # specify region of the cloud platform
          region: cn-south-1
          # specify bucket name of the cloud platform
          bucket: ${{ secrets.QINIU_BUCKET }}
          # specify exclude the given comma separated directories
          exclude: worker.js.map,index.js # optional
          # specify dist of the local directory
          dist: packages/common/dist/esm/
          # specify remote path for the files
          saveroot: modules/notice_master/packages/common/
        env:
          UPTOC_UPLOADER_AK: ${{ secrets.QINIU_ACCESS_KEY }}
          UPTOC_UPLOADER_SK: ${{ secrets.QINIU_SECRET_KEY }}

  
